version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:8.2.1
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: update yarn
          command: sudo npm install yarn@1.3.2 --global
      - restore_cache:
          keys:
            - v2-dependencies-node_modules-{{ arch }}-{{ checksum "yarn.lock" }}
      - run:
          name: install dependencies
          command: yarn
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-node_modules-{{ arch }}-{{ checksum "yarn.lock" }}
      - run:
          name: run linters
          command: yarn lint

  test:
    docker:
      - image: circleci/node:8.2.1
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: update yarn
          command: sudo npm install yarn@1.3.2 --global
      - restore_cache:
          keys:
            - v2-dependencies-node_modules-{{ arch }}-{{ checksum "yarn.lock" }}
      - run:
          name: install dependencies
          command: yarn
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-node_modules-{{ arch }}-{{ checksum "yarn.lock" }}
      - run:
          name: run tests
          command: yarn test

workflows:
  version: 2
  build:
    jobs:
      - lint
      - test